<?php
/**
 * Copyright © Magento, Inc. All rights reserved.
 * See COPYING.txt for license details.
 */
/**
 * @var \Magento\Payment\Block\Info $block
 * @see \Magento\Payment\Block\Info
 */
$config = $block->getLayout()->createBlock(\Magento\Config\Block\System\Config\Form::class);

$isTesting   = $config->getConfigValue('payment/myfatoorah_payment/is_testing');
$countryCode = $config->getConfigValue('payment/myfatoorah_payment/countryMode');

$scriptType    = $isTesting ? 'demo' : (($countryCode == 'SAU') ? 'sa' : 'portal');
$formScriptURL = 'https://' . $scriptType . '.myfatoorah.com/cardview/v1/session.js';
$apScriptURL   = 'https://' . $scriptType . '.myfatoorah.com/applepay/v2/applepay.js';
?>
<script>
    require.config({
        map: {
            '*': {
                'mfSessionFile': '<?=  $block->escapeHtml($formScriptURL); ?>',
                'mfAppleFile': '<?=  $block->escapeHtml($apScriptURL); ?>'

            }
        }
    });
</script>
